
### Path settings
path:
  expname: fsc-exp-test
  datadir: fsc_data/
  logdir: logs/fsc-progressive/


### rendering settings
render:
  mode: 'fsc'
  near: 0     #在这里去规定场景的大小
  far: 100      #在这里去规定场景的大小，这个就是最大5m范围，这就是文章中的D
  n_samples: 64
  scale_worldsize: 1


### training settings
train:
  lr: 1e-3
  weight_decay: 5e-5
  T_max: 10000
  eta_min: 1e-6
  batch_size: 16  #最好是2的幂，对硬件来说底层存储效率最大化
  total_iterations: 400  #70000
  load_ckpt: True

  save_freq: 100
  val_freq: 2500
  report_freq: 100


### network settings
networks:
  D: 8
  W: 256
  skips: [4]
  multires: {'pts': 10, 'view': 10, 'tx': 10}
  input_dims: {'pts': 3, 'view': 3, 'tx': 3}
  is_embeded: {'pts': True, 'view': True, 'tx': True}
  attn_output_dims: 2
  sig_output_dims: 2